CREATE TABLE site (id UUID PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, status VARCHAR(24) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO site(id,code,name,status) VALUES(CAST('10000000-0000-0000-0000-000000000001' AS UUID),'LAB-DEMO','Laboratoire fictif','ACTIVE');
ALTER TABLE equipment ADD COLUMN site_id UUID;
UPDATE equipment SET site_id=CAST('10000000-0000-0000-0000-000000000001' AS UUID);
ALTER TABLE equipment ALTER COLUMN site_id SET NOT NULL;
ALTER TABLE equipment ADD CONSTRAINT fk_equipment_site FOREIGN KEY(site_id) REFERENCES site(id);
CREATE INDEX idx_equipment_site ON equipment(site_id);

CREATE TABLE app_user (id UUID PRIMARY KEY, username VARCHAR(64) NOT NULL UNIQUE, email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(24) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT role_check CHECK(role IN ('ADMIN','NOC_OPERATOR','VIEWER')));
CREATE TABLE audit_entry (id UUID PRIMARY KEY, username VARCHAR(64), action VARCHAR(80) NOT NULL, target_type VARCHAR(80) NOT NULL, target_id UUID, details_sanitized VARCHAR(1000), performed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
